# Generated by Django 3.2.3 on 2021-06-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('createDateTime', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_wechat', models.IntegerField(blank=True, null=True)),
                ('amount_cash', models.IntegerField(blank=True, null=True)),
                ('amount_bank', models.IntegerField(blank=True, null=True)),
                ('amount_iou', models.IntegerField(blank=True, null=True)),
                ('amount_total', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(max_length=200)),
                ('createDateTime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SteelPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('createDateTime', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_tel', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('createDateTime', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
                ('createDateTime', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='WeightMemoOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight_own', models.FloatField(blank=True, null=True)),
                ('gross_weight_opposite', models.FloatField(blank=True, null=True)),
                ('body_weight_own', models.FloatField(blank=True, null=True)),
                ('body_weight_opposite', models.FloatField(blank=True, null=True)),
                ('deduct_weight', models.FloatField(blank=True, null=True)),
                ('legal_weight_own', models.FloatField(blank=True, null=True)),
                ('legal_weight_own_text', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_weight_opposite', models.FloatField(blank=True, null=True)),
                ('legal_weight_opposite_text', models.CharField(blank=True, max_length=100, null=True)),
                ('agreed_prise', models.IntegerField(blank=True, null=True)),
                ('actual_prise', models.IntegerField(blank=True, null=True)),
                ('expected_payment', models.IntegerField(blank=True, null=True)),
                ('expected_payment_text', models.CharField(blank=True, max_length=100, null=True)),
                ('opposite_payment', models.IntegerField(blank=True, null=True)),
                ('opposite_payment_text', models.CharField(blank=True, max_length=100, null=True)),
                ('advance_payment', models.IntegerField(blank=True, null=True)),
                ('rest_payment', models.IntegerField(blank=True, null=True)),
                ('actual_payment', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_done', models.BooleanField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('createDateTime', models.DateTimeField(verbose_name='date created')),
                ('complete_datetime', models.DateTimeField(blank=True, null=True)),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('advance_payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('rest_payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('intermediary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.intermediary')),
                ('steel_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.steelplant')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.truck')),
            ],
        ),
        migrations.CreateModel(
            name='WeightMemoIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.IntegerField(blank=True, null=True)),
                ('body_weight', models.IntegerField(blank=True, null=True)),
                ('deduct_weight', models.IntegerField(blank=True, null=True)),
                ('legal_weight', models.IntegerField(blank=True, null=True)),
                ('legal_prise', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('account_payable', models.IntegerField(blank=True, null=True)),
                ('actual_payment', models.IntegerField(blank=True, null=True)),
                ('account_payable_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_done', models.BooleanField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('createDateTime', models.DateTimeField(verbose_name='date created')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
            ],
        ),
    ]
